name: Continuous Integration

on:
 push:
   branches:
   - master
 pull_request:
   branches:
   - master
 schedule:
   - cron: '59 23 * * *'

jobs:
 unittests:
   name: conda (${{ matrix.os }}, ${{ matrix.environment-file }})
   runs-on: ${{ matrix.os }}
   timeout-minutes: 60
   strategy:
     matrix:
       os: ['macos-latest', 'ubuntu-latest', 'windows-latest']
       environment-file: [ci/36-PYPI.yaml, ci/36-GIT.yaml, ci/37-PYPI.yaml, ci/37-GIT.yaml, ci/38-PYPI.yaml, ci/38-GIT.yaml]
   steps:
     - uses: actions/checkout@v2
     - uses: goanpeca/setup-miniconda@v1
       with:
          miniconda-version: 'latest'
          auto-update-conda: true
          auto-activate-base: false
          environment-file: ${{ matrix.environment-file }}
          activate-environment: test
     - shell: bash -l {0}
       run: py.test -v giddy --cov=giddy --cov-report=xml
     - name: codecov (${{ matrix.os }}, ${{ matrix.environment-file }})
       uses: codecov/codecov-action@v1
       with:
         token: ${{ secrets.CODECOV_TOKEN }}
         file: ./coverage.xml
         name: giddy-codecov
